---
Name: silverstripepageprooferconfig
---
SilverStripe\SiteConfig\SiteConfig:
  extensions:
    - Muskie9\PageProofer\Extensions\PageProoferConfig
SilverStripe\CMS\Controllers\ContentController:
  extensions:
    - Muskie9\PageProofer\Extensions\PageProofer
